version: '3.8'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: allnagard/yamdb_web:v2

    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./static/:/var/www/static/
      - ./media/:/var/www/media/

  nginx:
    image: nginx:1.19.6
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/var/www/static/
      - ./media/:/var/www/media/
    depends_on:
      - web  