#version: '3.9'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: allnagard/yamdb_web:3
    restart: always
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_volume:/code/static  

  nginx:
    image: nginx:1.19.6
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/code/static/
      - ./media/:/code/media/
    depends_on:
      - web  